### ISSUE TITLE
Stream read method limitation

### ISSUE THREAD

**Issue by leometzger** [henryhamon/noodles#1]
Do pResponse.Data.Rewind()
Set tSC = ##class(%ZEN.Auxiliary.jsonProvider).%ConvertJSONToObject(pResponse.Data.Read(),,.json,1)

This method has a limitation of 32kb. Using a while loop, until "AtEnd()" is a better away to do it.

you're awesome 4kyu.

**Comment by henryhamon** [comment]
thanks for your note... I'll change it.

BTW,

>  kyus didn't fall from sky, you must deserve it 

[4 kyu on CodeWar xD](https://www.codewars.com/users/henryhamon)

**Comment by henryhamon** [comment]
That was fixed, thanks
